### PR TITLE
Feature/lgcs 404

### PR DESCRIPTION
**Pull request by joel-stobart**

### CODE REVIEW

**Comment by h0usemaintenance** [comment]
There are a number of errors in the log due to missing packages. Please take a look.

**Review by h0usemaintenance — CHANGES_REQUESTED** [review]
There are a number of exceptions in the PR build as well as when branch is run separately, please take a look.

**Review by h0usemaintenance — CHANGES_REQUESTED** [review]
- Please kindly remove the commented out export commands in scripts/travis/install.sh
- Are the multiple virtual environments created in this change for the whole cyber project repository once it is cloned into Travis?
-  Please ensure that $DATABASE_PASSWORD is removed from Travis if no longer required as you seem to be using $DATABASE_PASS.
- There is an error in the log: could not change directory to "/home/travis/build/WeAreSnook/cyber-health-frontend": Permission denied, any idea on what is causing it?
- If these are being installed through the requirements.txt, why add them to the CyberHealth/scripts/setup.sh?
Requirement already satisfied: wheel==0.36.2 in ./cyber-health-python/lib/python3.8/site-packages (from -r requirements.txt (line 31)) (0.36.2)
Requirement already satisfied: whitenoise==5.2.0 in ./cyber-health-python/lib/python3.8/site-packages (from -r requirements.txt (line 33)) (5.2.0)
Requirement already satisfied: psycopg2==2.8.6 in ./cyber-health-python/lib/python3.8/site-packages (from -r requirements.txt (line 35)) (2.8.6)
- There is an error in the log:  29 |             url = `${process.env.FRONTEND_PROTO}://${process.env.FRONTEND_HOST}:${process.env.FRONTEND_PORT}`
- Is there a full travis build run I can review as the one I can find is related to a pull request.

**Comment by joel-stobart** [comment]
- [x] **Please kindly remove the commented out export commands in scripts/travis/install.sh**
- [x] **Are the multiple virtual environments created in this change for the whole cyber project repository once it is cloned into Travis?** (No)
- [x] **Please ensure that $DATABASE_PASSWORD is removed from Travis if no longer required as you seem to be using $DATABASE_PASS**. I can't find $DATABASE_PASSWORD in the code or in the travis console.
- [ ] **There is an error in the log: could not change directory to "/home/travis/build/WeAreSnook/cyber-health-frontend": Permission denied, any idea on what is causing it?** My understanding is that it's trying to run bash for the postgres setup lines in the current directory. The postgres user doesn't have rights to that directory. 
- [ ] **If these are being installed through the requirements.txt, why add them to the CyberHealth/scripts/setup.sh?
Requirement already satisfied: wheel==0.36.2 in ./cyber-health-python/lib/python3.8/site-packages (from -r requirements.txt (line 31)) (0.36.2)** --> Because Wheel is required by safety 
- [x]  **Requirement already satisfied: whitenoise==5.2.0 in ./cyber-health-python/lib/python3.8/site-packages (from -r requirements.txt (line 33)) (5.2.0)**
- [x]  **Requirement already satisfied: psycopg2==2.8.6 in ./cyber-health-python/lib/python3.8/site-packages (from -r requirements.txt (line 35)) (2.8.6)**
- [ ]  **There is an error in the log: 29 | url = ${process.env.FRONTEND_PROTO}://${process.env.FRONTEND_HOST}:${process.env.FRONTEND_PORT}** I'll try an look into this with the new build
- [ ] **Is there a full travis build run I can review as the one I can find is related to a pull request.** No we don't run deployments on feature branches.

**Comment by joel-stobart** [comment]
Angela - this is the https://api.travis-ci.org/v3/job/767139600/log.txt. There is no mention of the FRONTEND_PROTO in that log.

**Comment by joel-stobart** [comment]
@h0usemaintenance  I think that addresses all of you comments.

**Comment by h0usemaintenance** [comment]
Any idea of why ${process.env.FRONTEND_PROTO}://${process.env.FRONTEND_HOST}:${process.env.FRONTEND_PORT}is coming up in that log? It doesn't seem to be in for example https://travis-ci.org/github/WeAreSnook/cyber-health-frontend/builds/767139892

**Comment by joel-stobart** [comment]
I have removed the console.log from the accessibility test code 

Could I ask what you want with "Also, can you please send me a link to a full build of the branch or an end to end run of the change to confirm that it will deploy successfully?" 

I can't do a full deploy on a feature branch. I'm trying to merge it into develop to run a deployment. Should that be successful it will deploy to staging and main. I don't want us to change the travis deploy file to deploy feature branches.

**Comment by h0usemaintenance** [comment]
Ok I didn't realize the develop branch was being used for testing. I will approve the change based on your comment above.

**Review by h0usemaintenance — APPROVED** [review]

**Pull request merged**
