### PR TITLE
Lgcs 575

### PR DESCRIPTION
**Pull request by joel-stobart**

### CODE REVIEW

**Review by kingdomlevel — APPROVED** [review]
Working for me locally - this is genuinely really exciting to see this data in the DB at this stage! 💪  Really really nice work 🏆

**Review by h0usemaintenance — APPROVED** [review]

**Comment by h0usemaintenance** [comment]
An amendment will need to be made at some point to ensure data can be loaded and objects can be created in the same run so that they are not done separately (as two different changes)

**Review by h0usemaintenance — COMMENTED** [review]
I notice you already merged PR 46 before this one, please resolve the merge conflict as the two had similar files.

**Comment by joel-stobart** [comment]
@h0usemaintenance  @kingdomlevel  could you please review this again, it should be a lot simpler :)

**Review by h0usemaintenance — APPROVED** [review]

**Pull request merged**
